app/models.py
from datetime import datetime

from flask_bcrypt import generate_password_hash, check_password_hash
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.ext.hybrid import hybrid_property

db = SQLAlchemy()

class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(), nullable=False)
    body = db.Column(db.Text(), nullable=False)

    created_at = db.Column(db.DateTime(), default=datetime.now)
    updated_at = db.Column(db.DateTime(), default=datetime.now, onupdate=datetime.now)
    published = db.Column(db.Boolean(), default=False)

    # created_by = db.relationship('User', backref='posts')
    # author_id = db.Column(db.Integer(), db.ForeignKey('user.id'), nullable=False, default=1)


class Comment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)


class User(db.Model):

    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(), nullable=False, unique=True)
    email = db.Column(db.String(), nullable=False, unique=True)
    _password = db.Column(db.String(), nullable=False)

    # posts = db.relationship('Post', backref='created_by', lazy=True)

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def password(self, text):
        self.password = generate_password_hash(text)

    def check_password(self, text):
        return check_password_hash(self.password, text)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, Length


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Body', validators=[DataRequired()])
    publish = BooleanField('Publish?')

    submit = SubmitField('submit')


class LoginForm(FlaskForm):
    username = StringField('Username:', [DataRequired(), Length(min=6)])
    password = PasswordField('Password:', [DataRequired(), Length(min=6)])
    remember = BooleanField('Remember me!')

    submit = SubmitField('Submit')


class RegisterForm(LoginForm):
    email = StringField('Email Address:', [DataRequired(), Email()])


class PasswordResetForm(FlaskForm):
    pass


class PasswordRecoveryForm(FlaskForm):
    pass

app/__init__.py
from flask import Flask
from flask_assets import Environment
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_migrate import Migrate
from flaskext.markdown import Markdown

app = Flask(__name__)
app.config.from_pyfile('config.py')

toolbar = DebugToolbarExtension(app)
Markdown(app)
bcrypt = Bcrypt(app)

assets = Environment(app)
assets.register('css', 'css/style.css', 'css/util.css', filters='cssmin', output='gen/main.css')
assets.register('js_all', 'js/script.js', filters='jsmin', output='gen/main.js')

assets.register('auth_style', 'css/auth.css', 'css/util.css', filters='cssmin', output='gen/auth.css', )
assets.register('auth_script', 'js/auth.js', filters='jsmin', output='gen/auth.js')

from .models import *

db.init_app(app)
migrate = Migrate(app, db)


@app.context_processor
def site_info():
    return dict(sitename='Juacy Willian')


from .views.core_bp import core
from .views.auth_bp import auth
from .views.admin_bp import admin

app.register_blueprint(core)
app.register_blueprint(auth)
app.register_blueprint(admin)

if __name__ == '__main__':
    app.run(debug=True)

app/views/admin_bp.py
from flask import Blueprint, request, flash, render_template, url_for, redirect

from ..forms import PostForm
from ..models import Post, db

admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/')
def dashboard():
    return render_template('admin/dashboard.html')


@admin.route('/new_post', methods=['GET', 'POST'])
def new_post():
    form = PostForm(**request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(
                title=form.title.data,
                body=form.body.data,
                published=form.publish.data)

            db.session.add(post)
            db.session.commit()
            flash('Post added successful.', 'success')
            if not post.published:
                flash('this post must be revised before published', 'info')

            return redirect(url_for('core.index'))
    return render_template('admin/new_post.html', form=form)


@admin.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
def edit_post(post_id):
    post = Post.query.get(post_id)
    form = PostForm(**request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            post.body = form.body.data
            post.published = form.publish.data

            db.session.add(post)
            db.session.commit()

            flash('post update successfull', 'success')
            return redirect(url_for('core.index'))
        else:
            pass

    form.title.data = post.title
    form.body.data = post.body
    form.publish.data = post.published

    return render_template('admin/edit_post.html', form=form, post_id=post.id)

app/views/auth_bp.py
from flask import Blueprint, request, render_template, flash

from ..forms import LoginForm, RegisterForm
from ..models import User

auth = Blueprint('auth', __name__, url_prefix='/auth')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(**request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data


            # todo: authentication

    return render_template('auth/login.html', form=form)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(**request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            password = form.password.data


            # todo: authentication

    return render_template('auth/register.html', form=form)


@auth.route('/password_reset', methods=['GET', 'POST'])
def password_reset():
    pass

app/views/core_bp.py
from flask import Blueprint, render_template, request, flash, url_for, redirect, abort
from sqlalchemy import desc, or_

from ..models import Post

core = Blueprint('core', __name__)


@core.route('/')
def index():
    posts = Post.query.filter_by(published=True).order_by(desc(Post.created_at)).all()
    return render_template('index.html', posts=posts)


@core.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get(post_id)
    if not post:
        abort(404)
    return render_template('post.html', post=post)


@core.route('/search', methods=['POST'])
def search():
    q = request.form['query']
    if q in ['', ' ', None]:
        flash('Invalid search!', 'error')
        return redirect(url_for('index'))

    result = Post.query.filter(Post.published == True) \
        .filter(
        or_(Post.title.contains(q), Post.body.contains(q))
    ).order_by(desc(Post.created_at)).all()
    return render_template('search.html', result=result)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/png" sizes="16x16">
    <title>{% block title %}{% endblock title %}</title>
    {% block styles %}{% endblock styles %}
</head>
<body>
{% block page_body %}{% endblock page_body %}

{% block scripts %}{% endblock scripts %}
</body>
</html>

app/templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="posts">
{% for post in posts %}
<div class="post">
    <h2>{{ post.title }}</h2>
    <div>{{ post.body|markdown }}</div>
</div>
{% endfor %}
</div>
{% endblock content %}

app/templates/layout.html
{% extends 'base.html' %}


{% block styles %}
{% assets 'css' %}
<link rel="stylesheet" href="{{ ASSET_URL }}" type="text/css">
{% endassets %}
{% endblock styles %}


{% block scripts %}
{% assets 'js_all' %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock scripts %}


{% block page_body %}

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="messages">
        {% for category, message in messages %}
        <p class="{{ category }}"><strong>{{ category }}:</strong> {{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    <div class="documentWrapper">
        <div class="bodyWrapper">
            <div class="header">
                <a href="{{ url_for('core.index') }}">
                    <img src="{{ url_for('static', filename='img/banner4.png') }}" alt="">
                </a>
            </div>
            <div class="content">
                {% block content %}{% endblock content %}
            </div>
        </div>
        <div class="sidebar">
            <h3>About Me!</h3>
            <p>Mollitia et sunt nemo ipsam assumenda voluptatibus. Repellat iure sed ipsum corporis.</p>
            <h3>Useful Links</h3>
            <ul>
                <li><a href="http://click.pocoo.org/">The Click Website</a></li>
                <li><a href="http://pypi.python.org/pypi/click">Click @ PyPI</a></li>
                <li><a href="http://github.com/mitsuhiko/click">Click @ github</a></li>
                <li><a href="http://github.com/mitsuhiko/click/issues">Issue Tracker</a></li>
            </ul>
            <h3>Versions</h3>
            <ul class="versions">
                <li>
                    <a href="." class="current">Development</a>
                    <span class="note">(unstable)</span>
                </li>
                <li>
                    <a href="./../6/">Click 6.x</a>
                    <span class="note">(stable)</span>
                </li>
                <li>
                    <a href="./../5/">Click 5.x</a>
                    <span class="note">(stable)</span>
                </li>
                <li>
                    <a href="./../4/">Click 4.x</a>
                </li>
            </ul>
            <div id="searchbox">
                <h3>Quick search</h3>
                <form class="search" action="{{ url_for('core.search') }}" method="post">
                    <input type="text" name="query" size="17">
                    <input type="submit" value="Go">
                </form>
            </div>
        </div>
        <div class="clearer"></div>
    </div>
    <div class="footer">
        © Copyright 2017, Juacy Willian.
        Inspired by <a href="http://sphinx.pocoo.org/">Sphinx</a>.
    </div>
</div>

{% endblock page_body %}

app/templates/search.html
{% extends 'layout.html' %}

{% block title %}Search Result{% endblock %}

{% block content %}

<h2>Search Result:</h2>

{% for post in result %}
    <h3>{{ post.title }}</h3>
    <div>{{ post.body|markdown }}</div>
{% endfor %}

{% endblock %}